server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cs2_market
    username: admin
    password: secretpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 10000
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_updates: true
        order_inserts: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/cs2-market
      client:
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: QtDRR8YGPQF53OKiBb2zGvmVAboR45hY
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/cs2-market

  springdoc:
   swagger-ui:
     path: http://localhost:8080/swagger-ui.html
   api-docs:
     path: http://localhost:8080/v3/api-docs
   oauth:
     clientId: springsecurity
     clientSecret: QtDRR8YGPQF53OKiBb2zGvmVAboR45hY
     authorizationUrl: "http://localhost:8180/realms/cs2-market/protocol/openid-connect/auth"
     tokenUrl: "http://localhost:8180/realms/cs2-market/protocol/openid-connect/token"
     scopes: openid, profile, email

logging:
  level:
    org.springframework.security: DEBUG